{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "68d79411-67ed-42bc-abeb-5b18255d8cc2",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Q1Explain why we have to use the exception class while creating a custom exception\n",
    "#The Exception class is the most basic class for exceptions in Python. It provides the basic functionality that all exceptions need,\n",
    "#Inheriting the Exception class allows the custom exception to have access to all of the built-in exception handling mechanisms in Python."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "1ec55a8f-78ca-4830-a918-210baddeeff6",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Exception hierarchy:\n",
      "---------------------\n",
      "TypeError\n",
      "  FloatOperation\n",
      "  MultipartConversionError\n",
      "StopAsyncIteration\n",
      "StopIteration\n",
      "ImportError\n",
      "  ModuleNotFoundError\n",
      "  ZipImportError\n",
      "OSError\n",
      "  ConnectionError\n",
      "  BlockingIOError\n",
      "  ChildProcessError\n",
      "  FileExistsError\n",
      "  FileNotFoundError\n",
      "  IsADirectoryError\n",
      "  NotADirectoryError\n",
      "  InterruptedError\n",
      "  PermissionError\n",
      "  ProcessLookupError\n",
      "  TimeoutError\n",
      "  UnsupportedOperation\n",
      "  itimer_error\n",
      "  herror\n",
      "  gaierror\n",
      "  SSLError\n",
      "  Error\n",
      "  SpecialFileError\n",
      "  ExecError\n",
      "  ReadError\n",
      "  URLError\n",
      "  BadGzipFile\n",
      "EOFError\n",
      "  IncompleteReadError\n",
      "RuntimeError\n",
      "  RecursionError\n",
      "  NotImplementedError\n",
      "  _DeadlockError\n",
      "  BrokenBarrierError\n",
      "  BrokenExecutor\n",
      "  SendfileNotAvailableError\n",
      "  ExtractionError\n",
      "  VariableError\n",
      "NameError\n",
      "  UnboundLocalError\n",
      "AttributeError\n",
      "  FrozenInstanceError\n",
      "SyntaxError\n",
      "  IndentationError\n",
      "LookupError\n",
      "  IndexError\n",
      "  KeyError\n",
      "  CodecRegistryError\n",
      "ValueError\n",
      "  UnicodeError\n",
      "  UnsupportedOperation\n",
      "  JSONDecodeError\n",
      "  SSLCertVerificationError\n",
      "  Error\n",
      "  UnsupportedDigestmodError\n",
      "  IllegalMonthError\n",
      "  IllegalWeekdayError\n",
      "  ParserError\n",
      "  ClassNotFound\n",
      "  ClipboardEmpty\n",
      "  MessageDefect\n",
      "  MacroToEdit\n",
      "  InvalidFileException\n",
      "  UnequalIterablesError\n",
      "  InvalidVersion\n",
      "  _InvalidELFFileHeader\n",
      "  InvalidWheelFilename\n",
      "  InvalidSdistFilename\n",
      "  InvalidSpecifier\n",
      "  InvalidMarker\n",
      "  UndefinedComparison\n",
      "  UndefinedEnvironmentName\n",
      "  InvalidRequirement\n",
      "  InvalidVersion\n",
      "AssertionError\n",
      "ArithmeticError\n",
      "  FloatingPointError\n",
      "  OverflowError\n",
      "  ZeroDivisionError\n",
      "  DecimalException\n",
      "SystemError\n",
      "  CodecRegistryError\n",
      "ReferenceError\n",
      "MemoryError\n",
      "BufferError\n",
      "Warning\n",
      "  UserWarning\n",
      "  EncodingWarning\n",
      "  DeprecationWarning\n",
      "  PendingDeprecationWarning\n",
      "  SyntaxWarning\n",
      "  RuntimeWarning\n",
      "  FutureWarning\n",
      "  ImportWarning\n",
      "  UnicodeWarning\n",
      "  BytesWarning\n",
      "  ResourceWarning\n",
      "  DeprecatedTzFormatWarning\n",
      "  PkgResourcesDeprecationWarning\n",
      "_OptionError\n",
      "_Error\n",
      "error\n",
      "Verbose\n",
      "Error\n",
      "SubprocessError\n",
      "  CalledProcessError\n",
      "  TimeoutExpired\n",
      "TokenError\n",
      "StopTokenizing\n",
      "ClassFoundException\n",
      "EndOfBlock\n",
      "TraitError\n",
      "Error\n",
      "Error\n",
      "  CancelledError\n",
      "  TimeoutError\n",
      "  InvalidStateError\n",
      "_GiveupOnSendfile\n",
      "error\n",
      "Incomplete\n",
      "TimeoutError\n",
      "InvalidStateError\n",
      "LimitOverrunError\n",
      "QueueEmpty\n",
      "QueueFull\n",
      "Empty\n",
      "Full\n",
      "ArgumentError\n",
      "ZMQBaseError\n",
      "  ZMQError\n",
      "  ZMQBindError\n",
      "  NotDone\n",
      "PickleError\n",
      "  PicklingError\n",
      "  UnpicklingError\n",
      "_Stop\n",
      "ArgumentError\n",
      "ArgumentTypeError\n",
      "ConfigError\n",
      "  ConfigLoaderError\n",
      "  ConfigFileNotFound\n",
      "ConfigurableError\n",
      "  MultipleInstanceError\n",
      "ApplicationError\n",
      "error\n",
      "TimeoutError\n",
      "error\n",
      "ReturnValueIgnoredError\n",
      "KeyReuseError\n",
      "UnknownKeyError\n",
      "LeakedCallbackError\n",
      "BadYieldError\n",
      "ReturnValueIgnoredError\n",
      "Return\n",
      "InvalidPortNumber\n",
      "error\n",
      "LZMAError\n",
      "RegistryError\n",
      "_GiveupOnFastCopy\n",
      "Error\n",
      "  NoSectionError\n",
      "  DuplicateSectionError\n",
      "  DuplicateOptionError\n",
      "  NoOptionError\n",
      "  InterpolationError\n",
      "  ParsingError\n",
      "NoIPAddresses\n",
      "BadZipFile\n",
      "LargeZipFile\n",
      "BadEntryPoint\n",
      "NoSuchEntryPoint\n",
      "DuplicateKernelError\n",
      "ErrorDuringImport\n",
      "NotOneValueFound\n",
      "CannotEval\n",
      "OptionError\n",
      "BdbQuit\n",
      "Restart\n",
      "ExceptionPexpect\n",
      "  EOF\n",
      "  TIMEOUT\n",
      "PtyProcessError\n",
      "FindCmdError\n",
      "HomeDirError\n",
      "ProfileDirError\n",
      "IPythonCoreError\n",
      "  TryNext\n",
      "  UsageError\n",
      "  StdinNotImplementedError\n",
      "InputRejected\n",
      "GetoptError\n",
      "ErrorToken\n",
      "PrefilterError\n",
      "AliasError\n",
      "  InvalidAliasError\n",
      "Error\n",
      "  InterfaceError\n",
      "  DatabaseError\n",
      "Warning\n",
      "SpaceInInput\n",
      "DOMException\n",
      "  IndexSizeErr\n",
      "  DomstringSizeErr\n",
      "  HierarchyRequestErr\n",
      "  WrongDocumentErr\n",
      "  InvalidCharacterErr\n",
      "  NoDataAllowedErr\n",
      "  NoModificationAllowedErr\n",
      "  NotFoundErr\n",
      "  NotSupportedErr\n",
      "  InuseAttributeErr\n",
      "  InvalidStateErr\n",
      "  SyntaxErr\n",
      "  InvalidModificationErr\n",
      "  NamespaceErr\n",
      "  InvalidAccessErr\n",
      "  ValidationErr\n",
      "ValidationError\n",
      "EditReadOnlyBuffer\n",
      "_Retry\n",
      "InvalidLayoutError\n",
      "HeightIsUnknownError\n",
      "ParserSyntaxError\n",
      "InternalParseError\n",
      "_PositionUpdatingFinished\n",
      "SimpleGetItemNotFound\n",
      "UncaughtAttributeError\n",
      "HasNoContext\n",
      "ParamIssue\n",
      "_JediError\n",
      "  InternalError\n",
      "  WrongVersion\n",
      "  RefactoringError\n",
      "OnErrorLeaf\n",
      "InvalidPythonEnvironment\n",
      "MessageError\n",
      "  MessageParseError\n",
      "  MultipartConversionError\n",
      "  CharsetError\n",
      "Error\n",
      "HTTPException\n",
      "  NotConnected\n",
      "  InvalidURL\n",
      "  UnknownProtocol\n",
      "  UnknownTransferEncoding\n",
      "  UnimplementedFileMode\n",
      "  IncompleteRead\n",
      "  ImproperConnectionState\n",
      "  BadStatusLine\n",
      "  LineTooLong\n",
      "InteractivelyDefined\n",
      "KillEmbedded\n",
      "Error\n",
      "  NoSuchProcess\n",
      "  AccessDenied\n",
      "  TimeoutExpired\n",
      "_Ipv6UnsupportedError\n",
      "QueueEmpty\n",
      "QueueFull\n",
      "DebuggerInitializationError\n",
      "ExpatError\n",
      "Error\n",
      "  ProtocolError\n",
      "  ResponseError\n",
      "  Fault\n",
      "ParseBaseException\n",
      "  ParseException\n",
      "  ParseFatalException\n",
      "RecursiveGrammarException\n",
      "ResolutionError\n",
      "  VersionConflict\n",
      "  DistributionNotFound\n",
      "  UnknownExtra\n",
      "_Error\n",
      "UnableToResolveVariableException\n",
      "InvalidTypeInArgsException\n"
     ]
    }
   ],
   "source": [
    "#Q2 Write a python program to print python Exception Hierarchy\n",
    "print(\"\\nException hierarchy:\")\n",
    "print(\"---------------------\")\n",
    "for cls in Exception.__subclasses__():\n",
    "    print(cls.__name__)\n",
    "    for subcls in cls.__subclasses__():\n",
    "        print(\"  {}\".format(subcls.__name__))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "49546218-9779-47fa-8c12-e9bdd260c1df",
   "metadata": {},
   "outputs": [
    {
     "ename": "ZeroDivisionError",
     "evalue": "division by zero",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mZeroDivisionError\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[2], line 6\u001b[0m\n\u001b[1;32m      4\u001b[0m p\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m10\u001b[39m\n\u001b[1;32m      5\u001b[0m q\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m0\u001b[39m\n\u001b[0;32m----> 6\u001b[0m r\u001b[38;5;241m=\u001b[39m\u001b[43mp\u001b[49m\u001b[38;5;241;43m/\u001b[39;49m\u001b[43mq\u001b[49m\n\u001b[1;32m      7\u001b[0m \u001b[38;5;66;03m#TypeError:This comes when we are performing an operation on two diffrent data types which is not permited.\u001b[39;00m\n\u001b[1;32m      8\u001b[0m z \u001b[38;5;241m=\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mseven\u001b[39m\u001b[38;5;124m\"\u001b[39m \u001b[38;5;241m+\u001b[39m \u001b[38;5;241m7\u001b[39m \n",
      "\u001b[0;31mZeroDivisionError\u001b[0m: division by zero"
     ]
    }
   ],
   "source": [
    "#Q3 What errors are defined in the Arithmetic class? Explain any two with an example.\n",
    "#exmaple1\n",
    "#ZeroDivisionError: comes when we try to divide a term with zero.\n",
    "p=10\n",
    "q=0\n",
    "r=p/q\n",
    "#TypeError:This comes when we are performing an operation on two diffrent data types which is not permited.\n",
    "z = \"seven\" + 7 "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "285d4f88-7424-4822-80b4-6b48c0a2b186",
   "metadata": {},
   "outputs": [
    {
     "ename": "KeyError",
     "evalue": "'Jack'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mKeyError\u001b[0m                                  Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[3], line 6\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[38;5;66;03m#Q4 Why LookupError class is used? Explain with an example KeyError and IndexError.\u001b[39;00m\n\u001b[1;32m      2\u001b[0m \u001b[38;5;66;03m#The LookupError class in Python is a base class for all lookup-related errors. It is used to represent the situations where an index or \u001b[39;00m\n\u001b[1;32m      3\u001b[0m \u001b[38;5;66;03m#a key is not found in a container like a list or a dictionary.The KeyError: is a type of LookupError that is raised when a dictionary key \u001b[39;00m\n\u001b[1;32m      4\u001b[0m \u001b[38;5;66;03m#is not found.\u001b[39;00m\n\u001b[1;32m      5\u001b[0m nameRoll \u001b[38;5;241m=\u001b[39m {\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mJon\u001b[39m\u001b[38;5;124m'\u001b[39m: \u001b[38;5;241m1\u001b[39m, \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mJony\u001b[39m\u001b[38;5;124m'\u001b[39m: \u001b[38;5;241m2\u001b[39m, \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mRony\u001b[39m\u001b[38;5;124m'\u001b[39m: \u001b[38;5;241m3\u001b[39m}\n\u001b[0;32m----> 6\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[43mnameRoll\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mJack\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m]\u001b[49m)\n",
      "\u001b[0;31mKeyError\u001b[0m: 'Jack'"
     ]
    }
   ],
   "source": [
    "#Q4 Why LookupError class is used? Explain with an example KeyError and IndexError.\n",
    "#The LookupError class in Python is a base class for all lookup-related errors. It is used to represent the situations where an index or \n",
    "#a key is not found in a container like a list or a dictionary.The KeyError: is a type of LookupError that is raised when a dictionary key \n",
    "#is not found.\n",
    "nameRoll = {'Jon': 1, 'Jony': 2, 'Rony': 3}\n",
    "print(nameRoll['Jack'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "316491a6-9cb5-429b-b6d7-fe973159c04b",
   "metadata": {},
   "outputs": [
    {
     "ename": "IndexError",
     "evalue": "list index out of range",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mIndexError\u001b[0m                                Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[4], line 3\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[38;5;66;03m#The IndexError is type of LookupError that is raised when an index is out of range.\u001b[39;00m\n\u001b[1;32m      2\u001b[0m myList \u001b[38;5;241m=\u001b[39m [\u001b[38;5;241m1\u001b[39m, \u001b[38;5;241m2\u001b[39m, \u001b[38;5;241m3\u001b[39m]\n\u001b[0;32m----> 3\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[43mmyList\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;241;43m3\u001b[39;49m\u001b[43m]\u001b[49m)\n",
      "\u001b[0;31mIndexError\u001b[0m: list index out of range"
     ]
    }
   ],
   "source": [
    "#The IndexError is type of LookupError that is raised when an index is out of range.\n",
    "myList = [1, 2, 3]\n",
    "print(myList[3])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "da527e7e-796a-408e-b727-4eaef146fa67",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "my_module not found\n"
     ]
    }
   ],
   "source": [
    "#Q5 Explain ImportError. What is ModuleNotFoundError?\n",
    "#ImportError: comes when we try to import modele or package but the import staement not work due to resons like:module is not installed,\n",
    "#modele is not in specified directory or module name is incorect.Python raises an ImportError with a message indicating that the specified\n",
    "#module could not be found.ImportError can also occur when there is an issue with the code inside the module.\n",
    "try:\n",
    "    import request\n",
    "except ImportError:\n",
    "    print(\"my_module not found\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "568d5319-4858-4d49-a82a-42ccf39af835",
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'mattplot'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[6], line 2\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[38;5;66;03m#ModuleNotFoundError: it was introduced as a subclass of ImportError. It is raised when a module is not found during an import statement. \u001b[39;00m\n\u001b[0;32m----> 2\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mmattplot\u001b[39;00m \u001b[38;5;66;03m#insted of matplotlib\u001b[39;00m\n",
      "\u001b[0;31mModuleNotFoundError\u001b[0m: No module named 'mattplot'"
     ]
    }
   ],
   "source": [
    "#ModuleNotFoundError: it was introduced as a subclass of ImportError. It is raised when a module is not found during an import statement. \n",
    "import mattplot #insted of matplotlib"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3486c660-aa04-44d0-b2b1-f605fefe5698",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Q6 List down some best practices for exception handling in python.\n",
    "\n",
    "#1.Using logging: We should use a logging framework to log exceptions and error messages. This can help to quickly identify issues and \n",
    "#debug problems.\n",
    "#2.Using finally blocks: We should use finally blocks to ensure that resources are properly closed, even if an exception is raised.\n",
    "#3.Handle exceptions appropriately: Handle exceptions in a way that is appropriate for the specific situation. For example, if you are \n",
    "#opening a file, handle FileNotFoundError by letting the user know that the file cannot be found.\n",
    "#4.Keep exception handling code separate: Write exception handling code separate from the code that caused the exception. This can make it \n",
    "#easier to read and understand the code, and can also make it easier to reuse the exception handling code."
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
